## Assignment - 1

### Part 1: Data Exploration with Pandas (30 Points)

#### Load the dataset

In [22]:
import pandas as pd

Cal_house_ds = pd.read_csv('california_housing_train.csv')
print(Cal_house_ds.head())
print(Cal_house_ds.tail(10))



   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124

#### Data Summary

In [23]:
Cal_house_ds.describe()


longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
print()
print(len(Cal_house_ds['total_bedrooms'].unique()))

Total unique elements in "total bedrooms" is : 1848
1848


#### Data Transformation

In [43]:
Cal_house_ds['total_bedrooms_per_total_rooms'] = Cal_house_ds['total_bedrooms']/Cal_house_ds['total_rooms']
print("Mean : " + str(Cal_house_ds['total_bedrooms_per_total_rooms'].mean()))
print("Standard Deviation : " + str(Cal_house_ds['total_bedrooms_per_total_rooms'].std()))

Mean : 0.21275998821034803
Standard Deviation : 0.05782300890316167


#### Data Filtering

In [46]:
Cal_house_ds.loc[Cal_house_ds['median_income']>5]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [50]:
Cal_house_ds_subset = Cal_house_ds.loc[(Cal_house_ds['total_rooms']>10000) & (Cal_house_ds['median_house_value']<150000)]
Cal_house_ds_subset

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

#### Export Modified Data

In [53]:
Cal_house_ds.to_csv('D:/Repositories/assignment_stackomatic/california_housing_train_updated.csv',index=False)

---

### Part 2: Numerical Analysis with NumPy (30 Points)

#### Array creation and indexing 

In [75]:
import numpy as np
int_arr = np.arange(1,21)
print(int_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [76]:
print(int_arr[1::2])

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
rand_2D_array = np.random.randint(10,100,(5,4))
print(rand_2D_array)


[[17 84 80 34]
 [50 61 16 75]
 [96 59 12 74]
 [67 78 26 49]
 [69 40 97 44]]


In [85]:
print(rand_2D_array[0:3,0:2])


[[17 84]
 [50 61]
 [96 59]]


#### Array Manipulation

In [87]:
int_arr = int_arr.reshape((4,5))
print(int_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
rand_2D_array = rand_2D_array.flatten()
print(rand_2D_array)

[17 84 80 34 50 61 16 75 96 59 12 74 67 78 26 49 69 40 97 44]


In [97]:
rand_2D_array_for_matrix_mul = np.random.randint(1,20,(5,4))
np.matmul(int_arr,rand_2D_array_for_matrix_mul)

array([[ 137,  194,  126,  162],
       [ 332,  484,  336,  442],
       [ 527,  774,  546,  722],
       [ 722, 1064,  756, 1002]])

#### Boolean and Fancy Indexing

In [99]:
ran_int_50 = np.random.randint(0,100,50)
print(ran_int_50)

[39 67 71 62 59 85 90 50 98 54 29 93  6 26 37 25 76 22 27 59  0 26 32 31
  5 90  8 39 15 21 83 95 68 69 76 96 86 16 44 84 35 67 29 98 90 49 57 82
 14 27]


In [ ]:
print(ran_int_50[ran_int_50>50]) 

[67 71 62 59 85 90 98 54 93 76 59 90 83 95 68 69 76 96 86 84 67 98 90 57
 82]


In [ ]:
print(ran_int_50[[0,7,34]]) # fancy indexing

[39 50 76]


#### Statistical Operations

In [108]:
print("ARRAY : ")
print(int_arr)
print("MEAN along each column: ")
print(int_arr.mean(axis=0))
print("MAX along each column: ")
print(int_arr.max(axis=0))
print("SUM along each column: ")
print(int_arr.sum(axis=0))

ARRAY : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
MEAN along each column: 
[ 8.5  9.5 10.5 11.5 12.5]
MAX along each column: 
[16 17 18 19 20]
SUM along each column: 
[34 38 42 46 50]


In [115]:

mask = int_arr>int_arr.mean(axis=0)
print(int_arr[mask])

[11 12 13 14 15 16 17 18 19 20]


---

### Part 3: Problem Solving with Python Basics (20 Points)

#### Loops and Conditional Statements

In [116]:
fibonacci = [0,1]
next_value = fibonacci[-1]+fibonacci[-2]
while next_value<100:
    fibonacci.append(next_value)
    next_value = fibonacci[-1]+fibonacci[-2]
print(fibonacci)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [119]:
i =1
while i in range(1,51):
    if(i%3==0):
        if(i%5==0):
            print(str(i) + " : FrizBuzz")
        else:
            print(str(i) + " : Fizz")
    if(i%5==0):
        print(str(i) + " : Buzz")
    i+=1

3 : Fizz
5 : Buzz
6 : Fizz
9 : Fizz
10 : Buzz
12 : Fizz
15 : FrizBuzz
15 : Buzz
18 : Fizz
20 : Buzz
21 : Fizz
24 : Fizz
25 : Buzz
27 : Fizz
30 : FrizBuzz
30 : Buzz
33 : Fizz
35 : Buzz
36 : Fizz
39 : Fizz
40 : Buzz
42 : Fizz
45 : FrizBuzz
45 : Buzz
48 : Fizz
50 : Buzz


#### Variable Length Arguments

In [123]:
def find_median(numbers):
    sorted_numbers = sorted(numbers)
    n = len(sorted_numbers)
    if n%2!=0:
        median = sorted_numbers[n//2]
    else:
        median = (sorted_numbers[n//2 - 1]+ sorted_numbers[n//2])/2
    return median

numbers = [1,5,2,9,3]
print("Median is " + str(find_median(numbers)))

    

Median is 3


In [125]:
def find_average(numbers):
    n = len(numbers)
    i = 0
    sum = 0
    while i in range(n):
        sum+=numbers[i]
        i+=1
    average = sum/n
    return average

numbers = [1,5,2,9,3]
print("Average is " + str(find_average(numbers)))

Average is 4.0


#### Error Handling

In [127]:
try:
    b = 0
    a = 4/b
except ZeroDivisionError:
    print("Division by zero is not possible")



Division by zero is not possible


---

### Part 4: Bonus Challenge (Optional) (20 Points)

#### Advanced NumPy Manipulation

In [128]:
import numpy as np

In [135]:
array_3d = np.random.rand(3,3,3)
print(array_3d)

[[[0.95816593 0.54887378 0.55567938]
  [0.98035787 0.88841302 0.27196193]
  [0.84109119 0.35403661 0.92320843]]

 [[0.82399289 0.60585604 0.55563275]
  [0.43549819 0.66409171 0.33761501]
  [0.41664408 0.10770016 0.71148646]]

 [[0.90099382 0.41375275 0.2834946 ]
  [0.12958515 0.55197112 0.5159872 ]
  [0.97540734 0.16309052 0.17057683]]]


In [136]:
np.swapaxes(array_3d,0,1)

array([[[0.95816593, 0.54887378, 0.55567938],
        [0.82399289, 0.60585604, 0.55563275],
        [0.90099382, 0.41375275, 0.2834946 ]],

       [[0.98035787, 0.88841302, 0.27196193],
        [0.43549819, 0.66409171, 0.33761501],
        [0.12958515, 0.55197112, 0.5159872 ]],

       [[0.84109119, 0.35403661, 0.92320843],
        [0.41664408, 0.10770016, 0.71148646],
        [0.97540734, 0.16309052, 0.17057683]]])

In [137]:
print("sums along a particular axis : " + str(array_3d.sum(axis=0)))

sums along a particular axis : [[2.68315264 1.56848256 1.39480674]
 [1.54544122 2.10447585 1.12556414]
 [2.23314261 0.62482729 1.80527172]]


In [141]:
rand_arr = np.random.randint(0,10,(3,3))
print("Original :")
print(rand_arr)
vector = np.array([1,3,6])
print("vector added random array : ")
print(rand_arr + vector)

Original :
[[7 1 1]
 [6 0 2]
 [6 2 9]]
vector added random array : 
[[ 8  4  7]
 [ 7  3  8]
 [ 7  5 15]]


---

# Assignment - 1 endedd